# Reverse Proxy
nginx:
    build: ./nginx
    links:
        - microservice1:microservice1
        - microservice2:microservice2
        - microservice3:microservice3
    ports:
        - "80:80"

# NodeJS RESTful API Microservice
microservice1:
    build: ./dist
    links:
        - mongo:mongo
    ports:
        - "9001:9000"
    environment:
        NODE_ENV: production
        MONGODB_URI: mongodb://mongo/service
microservice2:
    build: ./dist
    links:
        - mongo:mongo
    ports:
        - "9002:9000"
    environment:
        NODE_ENV: production
        MONGODB_URI: mongodb://mongo/service
microservice3:
    build: ./dist
    links:
        - mongo:mongo
    ports:
        - "9003:9000"
    environment:
        NODE_ENV: production
        MONGODB_URI: mongodb://mongo/service

# MongoDB
mongo:
    image: mongo
    ports:
        - "27017:27017"
